name: PR Approval Check

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Require Product Eng approval
        uses: trufflesecurity/pr-approval-check@v1   # <— just the repo + tag
        with:
          org: trufflesecurity
          approver_team: product-eng
          github_token: ${{ secrets.PR_APPROVAL_CHECK }}

